name: Build and Publish
on:
  push:
    branches:
      - main
jobs:
  build_docker_image:
    name: Build docker image and check any error TODO'Push later after the build'
    runs-on: ubuntu-latest
    steps:
      - name: Docker build and later push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false